const products = [
    {
      _id: "1",
      name: "زبدة الفول السوداني اكسترا بروتين",
      image: "/images/airpods.jpg",
      description:
        "Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working",
      brand: "JustFit",
      category: "Butter",
      price: 35.00,
      countInStock: 10,
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: "2",
      name: "زبدة الفول السوداني سادة",
      image: "/images/phone.jpg",
      description:
        "Introducing the iPhone 13 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life",
      brand: "JustFit",
      category: "Butter",
      price: 599.99,
      countInStock: 7,
      rating: 4.0,
      numReviews: 8,
    },
    {
      _id: "3",
      name: "زبدة الكاجو",
      image: "/images/camera.jpg",
      description:
        "Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design",
      brand: "JustFit",
      category: "Butter",
      price: 929.99,
      countInStock: 5,
      rating: 3,
      numReviews: 12,
    },
    {
      _id: "4",
      name: "زبدة اللوز",
      image: "/images/playstation.jpg",
      description:
        "The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music",
      brand: "JustFit",
      category: "Butter",
      price: 399.99,
      countInStock: 11,
      rating: 5,
      numReviews: 12,
    },
    {
      _id: "5",
      name: "شوكولاتة البندق",
      image: "/images/mouse.jpg",
      description:
        "Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience",
      brand: "JustFit",
      category: "Chocolate",
      price: 49.99,
      countInStock: 7,
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: "6",
      name: "كوكيز",
      image: "/images/alexa.jpg",
      description:
        "Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space",
      brand: "JustFit",
      category: "Cookies",
      price: 29.99,
      countInStock: 0,
      rating: 4,
      numReviews: 12,
  },
    {
      _id: "7",
      name: "قرانولا",
      image: "/images/alexa.jpg",
      description:
        "Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space",
      brand: "JustFit",
      category: "Granola",
      price: 29.99,
      countInStock: 4,
      rating: 4,
      numReviews: 15,
  },
  ];
   
  export default products;